version: "3"
services:
    api:
        build: 
            context: ./
            dockerfile: ./api/Dockerfile
        env_file: .env
        ports:
             - "8000:1337"
    
    timelapse:
        build:
            context: ./
            dockerfile: ./timelapse/Dockerfile
        env_file: .env
    
    liveviews:
        build:
            context: ./
            dockerfile: ./liveviews/Dockerfile
        env_file: .env